---
spring:
  application:
    name: pal-tracker
  datasource:
    url: jdbc:mysql://localhost:3306/tracker_test?user=tracker&useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false

welcome_message: Hello from test